<?php
/** @var \AHT\AHTtest\Block\Template $block */
$data = $block->getTable();
?>
<div class="template">
    <h1 >Edit</h1>
    <form action="<?=$block->getBaseUrl()?>hihi/index/save" method="post">
        <input name="name" value="<?= $data->getName() ?>">
        <input name="age" value="<?= $data->getAge() ?>">
    
        <input type="hidden" name="table_id" value="<?= $data->getTableID() ?>">
        <button type="submit">Submit</button>
   </form>
</div>